- task: ServiceNow-DevOps-Agent-Artifact-Registration@1
  inputs:
    connectedServiceName: 'Azure DevOps ServiceNow'
    artifactsPayload: |
      {
         "artifacts": [
            {
               "name": "TestArtifact1",
               "version": "1.$(Build.BuildId)",
               "semanticVersion": "1.$(Build.BuildId).0",
               "repositoryName": "TestRepo"
            }
         ]
      }